# Background and foreground colors
background = #241D22
foreground = #f0ecc5

# Standard colors
palette = 0=#241D22
palette = 1=#a58386
palette = 2=#83c483
palette = 3=#c1ba86
palette = 4=#a3baca
palette = 5=#e19567
palette = 6=#a2c5d2
palette = 7=#f0ecc5

# Bright colors
palette = 8=#998d96
palette = 9=#cdb7b9
palette = 10=#80c880
palette = 11=#b9ae6a
palette = 12=#bad6e3
palette = 13=#e7aa86
palette = 14=#c4dce5
palette = 15=#f0ecc5

# Transparency
background-opacity = 0.8