background            #241D22
foreground            #f0ecc5

# black
color0  #241D22
color8  #998d96

# red
color1  #a58386
color9  #cdb7b9

# green
color2  #83c483
color10 #80c880

# yellow
color3  #c1ba86
color11 #b9ae6a

# blue
color4  #a3baca
color12 #bad6e3

# magenta
color5  #e19567
color13 #e7aa86

#cyan
color6  #a2c5d2
color14 #c4dce5

#white
color7  #f0ecc5
color15 #f0ecc5

# Transparency
background_opacity 0.8